spring:
  application:
    name: backend
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://192.168.1.8:30432/bytecub?currentSchema=wedahamine&useSSL=false&serverTimezone=UTC
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver
  hikari:
    poolName: Hikari
    auto-commit: false
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
    minimum-idle: 2
    maximum-pool-size: 5
    idle-timeout: 120000
    connection-timeout: 300000
    leak-detection-threshold: 300000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: kotuwegedarawedahamine@gmail.com
    password: 'wvqn sfei cmrs xqse'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 8080
  servlet:
    context-path: /api/wedahamine/v1

app:
#  base-url: http://localhost:8080/api/wedahamine/v1
  base-url: http://192.168.1.8:30088/api/wedahamine/v1

logging:
  file:
    name: ${spring.application.name}.log