package org.bytecub.WedahamineBackend.constants;

public class EmailTemplates {

    public static final String USER_CREATION_EMAIL_SUBJECT = "🌿 Welcome to Wedahamine! Verify Your Account to Get Started";
    public static final String USER_CREATION_EMAIL_CONTENT = "<!DOCTYPE html>"
            + "<html>"
            + "<head>"
            + "<style>"
            + "  body { font-family: Arial, sans-serif; color: #333333; }"
            + "  .container { width: 100%; max-width: 600px; margin: 0 auto; padding: 20px; }"
            + "  .header { text-align: center; padding-bottom: 20px; }"
            + "  .content { background-color: #ffffff; padding: 20px; border-radius: 8px; }"
            + "  .footer { font-size: 12px; text-align: center; color: #777777; padding-top: 20px; }"
            + "  h1 { color: #4CAF50; }"
            + "  p { line-height: 1.6; }"
            + "</style>"
            + "</head>"
            + "<body>"
            + "<div class='container'>"
            + "  <div class='header'>"
            + "    <h1>Welcome to Wedahamine, {{firstName}}!</h1>"
            + "  </div>"
            + "  <div class='content'>"
            + "    <p>✨ Congratulations! Your account has been successfully created on <strong>Wedahamine</strong>, your trusted partner for Ayurvedic wellness and healing. We’re delighted to have you join our community!</p>"
            + "    <hr>"
            + "    <p><strong>Your Account Details:</strong><br>"
            + "       Username: <strong>{{username}}</strong><br>"
            + "       Member ID: <strong>{{userId}}</strong></p>"
            + "    <p>Please keep these details safe and secure.</p>"
            + "    <hr>"
            + "    <h2>Verify Your Account</h2>"
            + "    <p>To complete the registration process, please verify your account by clicking the link below:</p>"
            + "    <p><a href='{{verificationLink}}' style='color: #4CAF50; font-weight: bold;'>Verify My Account</a></p>"
            + "    <p>If the link doesn't work, copy and paste the following URL into your browser:</p>"
            + "    <p>{{verificationLink}}</p>"
            + "    <hr>"
            + "    <h2>What’s Next?</h2>"
            + "    <ul>"
            + "      <li>Explore our dispensary of Ayurvedic products and find the essentials tailored to your needs.</li>"
            + "      <li>Book consultations with Ayurvedic experts.</li>"
            + "      <li>Discover personalized wellness tips crafted by experts.</li>"
            + "    </ul>"
            + "    <p>Thank you for choosing Wedahamine. We’re excited to support you on your path to a healthier, balanced life!</p>"
            + "    <p style='font-weight: bold;'>Stay connected: Be sure to check your inbox for wellness tips, exclusive updates, and offers.</p>"
            + "  </div>"
            + "  <div class='footer'>"
            + "    <p>If you need support, contact us at <a href='mailto:support@wedahamine.com'>support@wedahamine.com</a>.</p>"
            + "    <p>Follow us on <a href='https://facebook.com/wedahamine'>Facebook</a> and <a href='https://instagram.com/wedahamine'>Instagram</a> to stay updated on all things Ayurveda!</p>"
            + "  </div>"
            + "</div>"
            + "</body>"
            + "</html>";

    public static final String EXPIRED_LINK_EMAIL_SUBJECT = "⚠️ Verification Link Expired - Resend Request to Verify Your Account";
    public static final String EXPIRED_LINK_EMAIL_CONTENT = "<!DOCTYPE html>"
        + "<html>"
        + "<head>"
        + "<style>"
        + "  body { font-family: Arial, sans-serif; color: #333333; }"
        + "  .container { width: 100%; max-width: 600px; margin: 0 auto; padding: 20px; }"
        + "  .header { text-align: center; padding-bottom: 20px; }"
        + "  .content { background-color: #ffffff; padding: 20px; border-radius: 8px; }"
        + "  .footer { font-size: 12px; text-align: center; color: #777777; padding-top: 20px; }"
        + "  h1 { color: #FF5722; }"
        + "  p { line-height: 1.6; }"
        + "</style>"
        + "</head>"
        + "<body>"
        + "<div class='container'>"
        + "  <div class='header'>"
        + "    <h1>Verify Your Account, {{firstName}}</h1>"
        + "  </div>"
        + "  <div class='content'>"
        + "    <p>⚠️ The verification link we sent earlier has expired. But don’t worry, we’ve got you covered!</p>"
        + "    <p>To verify your account and start exploring <strong>Wedahamine</strong>, simply click the link below to verify your account:</p>"
        + "    <p><a href='{{newVerificationLink}}' style='color: #FF5722; font-weight: bold;'>Click Here To Verify</a></p>"
        + "    <p>If the link doesn't work, copy and paste the following URL into your browser:</p>"
        + "    <p>{{newVerificationLink}}</p>"
        + "    <hr>"
        + "    <h2>Why Verify Your Account?</h2>"
        + "    <p>Verification ensures that you can:</p>"
        + "    <ul>"
        + "      <li>Access personalized Ayurvedic wellness tips.</li>"
        + "      <li>Shop premium Ayurvedic products.</li>"
        + "      <li>Book expert consultations with ease.</li>"
        + "    </ul>"
        + "    <p>💡 If you didn’t request this email or have already verified your account, please ignore this message.</p>"
        + "  </div>"
        + "  <div class='footer'>"
        + "    <p>If you need assistance, contact us at <a href='mailto:support@wedahamine.com'>support@wedahamine.com</a>.</p>"
        + "    <p>Stay updated on <a href='https://facebook.com/wedahamine'>Facebook</a> and <a href='https://instagram.com/wedahamine'>Instagram</a>.</p>"
        + "  </div>"
        + "</div>"
        + "</body>"
        + "</html>";

    public static final String PASSWORD_RESET_EMAIL_SUBJECT = "🔑 Reset Your Password - OTP Verification";
    public static final String PASSWORD_RESET_EMAIL_CONTENT = "Dear User,<br><br>Your OTP for resetting your password is: <strong>{{otp}}</strong>.<br>"
            + "Please use this OTP within 10 minutes to reset your password.<br><br>"
            + "If you did not request this, please ignore this email.<br><br>Thank you,<br>Wedahamine Team.";

    public static final String PASSWORD_RESET_SUCCESS_EMAIL_SUBJECT = "✅ Password Reset Successful - Access Restored";
    public static final String PASSWORD_RESET_SUCCESS_EMAIL_CONTENT = "<!DOCTYPE html>"
        + "<html>"
        + "<head>"
        + "<style>"
        + "  body { font-family: Arial, sans-serif; color: #333333; }"
        + "  .container { width: 100%; max-width: 600px; margin: 0 auto; padding: 20px; }"
        + "  .header { text-align: center; padding-bottom: 20px; }"
        + "  .content { background-color: #ffffff; padding: 20px; border-radius: 8px; }"
        + "  .footer { font-size: 12px; text-align: center; color: #777777; padding-top: 20px; }"
        + "  h1 { color: #4CAF50; }"
        + "  p { line-height: 1.6; }"
        + "</style>"
        + "</head>"
        + "<body>"
        + "<div class='container'>"
        + "  <div class='header'>"
        + "    <h1>Password Reset Successful!</h1>"
        + "  </div>"
        + "  <div class='content'>"
        + "    <p>Dear {{firstName}},</p>"
        + "    <p>We wanted to let you know that your password has been successfully reset. You can now log in to your <strong>Wedahamine</strong> account with your new password.</p>"
        + "    <hr>"
        + "    <h2>What to Do Next?</h2>"
        + "    <ul>"
        + "      <li>Log in to your account to ensure everything works as expected.</li>"
        + "      <li>If you face any issues, reach out to our support team.</li>"
        + "      <li>For your security, avoid sharing your password with anyone.</li>"
        + "    </ul>"
        + "    <p>💡 If you did not initiate this password reset, please contact our support team immediately at <a href='mailto:support@wedahamine.com'>support@wedahamine.com</a>.</p>"
        + "    <p>Thank you for trusting <strong>Wedahamine</strong>. We’re always here to help you on your wellness journey!</p>"
        + "  </div>"
        + "  <div class='footer'>"
        + "    <p>If you need assistance, contact us at <a href='mailto:support@wedahamine.com'>support@wedahamine.com</a>.</p>"
        + "    <p>Stay updated on <a href='https://facebook.com/wedahamine'>Facebook</a> and <a href='https://instagram.com/wedahamine'>Instagram</a>.</p>"
        + "  </div>"
        + "</div>"
        + "</body>"
        + "</html>";

    public static final String CHANGE_PASSWORD_SUCCESS_EMAIL_SUBJECT = "🔒 Password Changed Successfully - Account Secured";
    public static final String CHANGE_PASSWORD_SUCCESS_EMAIL_CONTENT = "<!DOCTYPE html>"
        + "<html>"
        + "<head>"
        + "<style>"
        + "  body { font-family: Arial, sans-serif; color: #333333; }"
        + "  .container { width: 100%; max-width: 600px; margin: 0 auto; padding: 20px; }"
        + "  .header { text-align: center; padding-bottom: 20px; }"
        + "  .content { background-color: #ffffff; padding: 20px; border-radius: 8px; }"
        + "  .footer { font-size: 12px; text-align: center; color: #777777; padding-top: 20px; }"
        + "  h1 { color: #4CAF50; }"
        + "  p { line-height: 1.6; }"
        + "</style>"
        + "</head>"
        + "<body>"
        + "<div class='container'>"
        + "  <div class='header'>"
        + "    <h1>Password Changed Successfully!</h1>"
        + "  </div>"
        + "  <div class='content'>"
        + "    <p>Dear {{firstName}},</p>"
        + "    <p>We’re writing to confirm that your password has been successfully changed. Your account is now updated with the new password you’ve set.</p>"
        + "    <hr>"
        + "    <h2>Account Security Tips:</h2>"
        + "    <ul>"
        + "      <li>Ensure your password is unique and not shared with anyone.</li>"
        + "      <li>Update your password regularly to maintain account security.</li>"
        + "      <li>Contact us immediately if you notice any suspicious activity in your account.</li>"
        + "    </ul>"
        + "    <p>💡 If you did not request this password change, please contact our support team immediately at <a href='mailto:support@wedahamine.com'>support@wedahamine.com</a>.</p>"
        + "    <p>Thank you for choosing <strong>Wedahamine</strong>. Your security is our top priority!</p>"
        + "  </div>"
        + "  <div class='footer'>"
        + "    <p>If you need assistance, contact us at <a href='mailto:support@wedahamine.com'>support@wedahamine.com</a>.</p>"
        + "    <p>Stay updated on <a href='https://facebook.com/wedahamine'>Facebook</a> and <a href='https://instagram.com/wedahamine'>Instagram</a>.</p>"
        + "  </div>"
        + "</div>"
        + "</body>"
        + "</html>";



}
