package org.bytecub.WedahamineBackend.constants;

public class EmailTemplates {

    public static final String USER_CREATION_EMAIL_SUBJECT = "🎉 Welcome to Wedahamine! Your Account Has Been Successfully Created";
    public static final String USER_CREATION_EMAIL_CONTENT = "<!DOCTYPE html>"
            + "<html>"
            + "<head>"
            + "<style>"
            + "  body { font-family: Arial, sans-serif; color: #333333; }"
            + "  .container { width: 100%; max-width: 600px; margin: 0 auto; padding: 20px; }"
            + "  .header { text-align: center; padding-bottom: 20px; }"
            + "  .content { background-color: #ffffff; padding: 20px; border-radius: 8px; }"
            + "  .footer { font-size: 12px; text-align: center; color: #777777; padding-top: 20px; }"
            + "  h1 { color: #4CAF50; }"
            + "  p { line-height: 1.6; }"
            + "</style>"
            + "</head>"
            + "<body>"
            + "<div class='container'>"
            + "  <div class='header'>"
            + "    <h1>Welcome to Wedahamine, {{firstName}} !</h1>"
            + "  </div>"
            + "  <div class='content'>"
            + "    <p>✨ Congratulations! Your account has been successfully created on <strong>Wedahamine</strong>, your trusted partner for Ayurvedic wellness and healing. We’re delighted to have you join our community!</p>"
            + "    <hr>"
            + "    <p><strong>Your Account Details:</strong><br>"
            + "       Username: <strong> {{username}} </strong><br>"
            + "       Member ID: <strong> {{userId}} </strong></p>"
            + "    <p>Please keep these details safe and secure.</p>"
            + "    <hr>"
            + "    <h2>What’s Next?</h2>"
            + "    <ul>"
            + "      <li>Explore our dispensary of Ayurvedic products and find the essentials tailored to your needs.</li>"
            + "      <li>Book consultations with Ayurvedic experts.</li>"
            + "      <li>Discover personalized wellness tips crafted by experts.</li>"
            + "    </ul>"
            + "    <p>Thank you for choosing Wedahamine. We’re excited to support you on your path to a healthier, balanced life!</p>"
            + "    <p style='font-weight: bold;'>Stay connected: Be sure to check your inbox for wellness tips, exclusive updates, and offers.</p>"
            + "  </div>"
            + "  <div class='footer'>"
            + "    <p>If you need support, contact us at <a href='mailto:support@wedahamine.com'>support@wedahamine.com</a>.</p>"
            + "    <p>Follow us on <a href='https://facebook.com/wedahamine'>Facebook</a> and <a href='https://instagram.com/wedahamine'>Instagram</a> to stay updated on all things Ayurveda!</p>"
            + "  </div>"
            + "</div>"
            + "</body>"
            + "</html>";

}
